### ISSUE TITLE
IPower Conflict during build

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_device_xiaomi_spes#5]
![IMG_20240407_022140_221](https://github.com/crdroidandroid/android_device_xiaomi_spes/assets/62609322/f1165fa5-2bb1-4d7a-a304-772c6ecddc41)

Here's the log
https://termbin.com/9gtx

**Comment by neobuddy89** [comment]
Clearly issue in your Device Tree. Check if you  copying power xml separately  in vendor.
